server:
  port: 8080

spring:
  application:
    name: food-ai-assistant-backend

foodai:
  cors:
    allowed-origins: http://localhost:5173
  security:
    api-key: ""
  rate-limit:
    requests-per-minute: 10
  ai:
    provider: ollama
    model-name: qwen2.5:3b
    api-key: ""
    base-url: http://localhost:11434
